### ISSUE TITLE
Make the crate `no_std` comptable

### ISSUE THREAD

**Issue by frisitano** [frisitano/merkle-tree-db#9]
We should make the crate `no_std` compatible by introducing a `std` feature flag.  This will allow the library to function in `no_std` environments.

**Comment by Ankitwasnik** [comment]
Hi @frisitano,

I have the changes to fix this issue on my local machine. Can you grant me access to this repo so that I can raise a PR?

**Comment by frisitano** [comment]
> Hi @frisitano,
> 
> I have the changes to fix this issue on my local machine. Can you grant me access to this repo so that I can raise a PR?

Done and assigned to you.l
